### ISSUE TITLE
I/O Exceptions in MatomoAnalytics ctor on Android & iOS

### ISSUE THREAD

**Issue by janusw** [bfn-tech/Matomo.Maui#6]
I tried to vaguely follow the initial-setup procedure from https://github.com/bnotech/Matomo.Xamarin.Forms/blob/main/README.md#initial-setup (which is unfortunately missing for Matomo.Maui). However, whenever I try to use Matomo.Maui v7.1.1 in a net8.0 app, e.g. via `MatomoAnalytics.TrackPage`, I get I/O exceptions inside the `MatomoAnalytics` constructor, both on Android and iOS.

Exception on Android 14:
```
System.IO.IOException: Read-only file system : '/matomodata.json'
  at at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
  at at Interop.CheckIo(Error error, String path, Boolean isDirError)
  at at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
  at at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
  at at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode, Func`4 createOpenException)
  at at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
  at at System.IO.Strategies.UnixFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
  at at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
  at at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
  at at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
  at at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
  at at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
  at at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
  at at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
  at at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize)
  at at System.IO.StreamWriter..ctor(String path, Boolean append)
  at at System.IO.File.CreateText(String path)
  at at Matomo.Maui.SimpleStorage.WriteToDisk()
  at at Matomo.Maui.SimpleStorage.Put[String](String key, String value)
  at at Matomo.Maui.MatomoAnalytics..ctor(String apiUrl, Int32 siteId)
```

Exception on iOS 18:
```
Exception has occurred: System.UnauthorizedAccessException
Access to the path '/private/var/containers/Bundle/Application/CCC5627A-32C5-4C5D-B0A5-ED02E15AF4B3/MyApp.app/matomodata.json' is denied.
    at at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
    at at Interop.CheckIo(Error error, String path, Boolean isDirError)
    at at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
    at at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
    at at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode, Func`4 createOpenException)
    at at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
    at at System.IO.Strategies.UnixFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
    at at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
    at at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
    at at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
    at at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
    at at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
    at at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
    at at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
    at at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize)
    at at System.IO.StreamWriter..ctor(String path, Boolean append)
    at at System.IO.File.CreateText(String path)
    at at Matomo.Maui.SimpleStorage.WriteToDisk()
    at at Matomo.Maui.SimpleStorage.Put[String](String key, String value)
    at at Matomo.Maui.MatomoAnalytics..ctor(String apiUrl, Int32 siteId)
```

**Comment by janusw** [comment]
I just noticed that there is a fork of the the repo, which should probably fix the problem via this commit (by @Alex-Witkowski): https://github.com/DevelappersGmbH/Matomo.Maui/commit/214ba5a4eaea628006a6c6ff09c60af561ffb615

**Comment by janusw** [comment]
So, the question is how to move forward here. @bnoffer Are you going to keep on maintaining this repo, or have you abandoned it?

If the former, we should create a PR for the changes from https://github.com/DevelappersGmbH/Matomo.Maui/commits/Refactoring/.

If the latter, we have to think of something else. Either @Alex-Witkowski could take over maintainership, or we move the repo into a shared org on GitHub, where we can maintain it together. What do you think, guys?

**Comment by bnoffer** [comment]
Hi @janusw,

thank you very much for your report. I had planned on updating the project to .NET 8 for a while and we were busy with client work. However this project now has come back into focus and I just performed a major refactoring. 

I will check your recommendation and include it in the next update. The reference documentation and the sample App have been updated as well as a getting started section was added to the README.

There should be a new preview version out shortly.

**Comment by janusw** [comment]
> However this project now has come back into focus and I just performed a major refactoring.
> 
> I will check your recommendation and include it in the next update. The reference documentation and the sample App have been updated as well as a getting started section was added to the README.
> 
> There should be a new preview version out shortly.

Sounds great, thanks for the update! 👍

**Comment by janusw** [comment]
Just tried the new packages: With 8.0.0-pre004 the exceptions above still occur, but I can confirm that they are gone with 8.0.0-pre005. Thanks for fixing! 🥳

**Comment by bnoffer** [comment]
Thank you for checking as well. I will be working on integrating the library in a production solution today. If everything goes well I plan on releasing v. 8.0.0.

**Comment by janusw** [comment]
I'll also do some further checking and evaluation. If no bigger issues come up, we might use the library for a production app as well.
